[2024-04-23T14:53:18.380+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T14:53:18.406+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T14:53:08.009919+00:00 [queued]>
[2024-04-23T14:53:18.417+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T14:53:08.009919+00:00 [queued]>
[2024-04-23T14:53:18.419+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-23T14:53:18.436+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): data_quality_check> on 2024-04-23 14:53:08.009919+00:00
[2024-04-23T14:53:18.447+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=679) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-23T14:53:18.449+0000] {standard_task_runner.py:63} INFO - Started process 688 to run task
[2024-04-23T14:53:18.449+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'data_quality_check', 'manual__2024-04-23T14:53:08.009919+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpw4wn1vc8']
[2024-04-23T14:53:18.451+0000] {standard_task_runner.py:91} INFO - Job 102: Subtask data_quality_check
[2024-04-23T14:53:18.511+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T14:53:08.009919+00:00 [running]> on host ec31c9b90297
[2024-04-23T14:53:18.633+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='data_quality_check' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T14:53:08.009919+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T14:53:08.009919+00:00'
[2024-04-23T14:53:18.635+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T14:53:19.355+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-23T14:53:19.356+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T14:53:19.368+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=model_pipeline, task_id=data_quality_check, execution_date=20240423T145308, start_date=20240423T145318, end_date=20240423T145319
[2024-04-23T14:53:19.431+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-23T14:53:19.470+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-23T14:53:19.473+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
