[2024-04-23T16:22:14.902+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T16:22:14.971+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.generate_report manual__2024-04-23T16:13:57.006623+00:00 [queued]>
[2024-04-23T16:22:14.995+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.generate_report manual__2024-04-23T16:13:57.006623+00:00 [queued]>
[2024-04-23T16:22:15.004+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2024-04-23T16:22:15.062+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_report> on 2024-04-23 16:13:57.006623+00:00
[2024-04-23T16:22:15.089+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=272) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-23T16:22:15.093+0000] {standard_task_runner.py:63} INFO - Started process 281 to run task
[2024-04-23T16:22:15.094+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'generate_report', 'manual__2024-04-23T16:13:57.006623+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpmm_s5sk3']
[2024-04-23T16:22:15.100+0000] {standard_task_runner.py:91} INFO - Job 147: Subtask generate_report
[2024-04-23T16:22:15.249+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.generate_report manual__2024-04-23T16:13:57.006623+00:00 [running]> on host 66b63a6c230d
[2024-04-23T16:22:15.913+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='generate_report' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T16:13:57.006623+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T16:13:57.006623+00:00'
[2024-04-23T16:22:15.919+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T16:22:17.131+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-23T16:22:17.134+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T16:22:17.170+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=model_pipeline, task_id=generate_report, execution_date=20240423T161357, start_date=20240423T162214, end_date=20240423T162217
[2024-04-23T16:22:17.233+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-23T16:22:17.271+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T16:22:17.274+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
