[2024-04-23T15:00:25.707+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T15:00:25.734+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T15:00:14.601490+00:00 [queued]>
[2024-04-23T15:00:25.744+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T15:00:14.601490+00:00 [queued]>
[2024-04-23T15:00:25.745+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-23T15:00:25.763+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): data_quality_check> on 2024-04-23 15:00:14.601490+00:00
[2024-04-23T15:00:25.774+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=843) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-23T15:00:25.776+0000] {standard_task_runner.py:63} INFO - Started process 852 to run task
[2024-04-23T15:00:25.776+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'data_quality_check', 'manual__2024-04-23T15:00:14.601490+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp5_3n5g5n']
[2024-04-23T15:00:25.778+0000] {standard_task_runner.py:91} INFO - Job 106: Subtask data_quality_check
[2024-04-23T15:00:25.849+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T15:00:14.601490+00:00 [running]> on host ec31c9b90297
[2024-04-23T15:00:25.981+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='data_quality_check' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T15:00:14.601490+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T15:00:14.601490+00:00'
[2024-04-23T15:00:25.984+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T15:00:26.631+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-23T15:00:26.632+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T15:00:26.643+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=model_pipeline, task_id=data_quality_check, execution_date=20240423T150014, start_date=20240423T150025, end_date=20240423T150026
[2024-04-23T15:00:26.677+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-23T15:00:26.710+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-23T15:00:26.713+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
