[2024-04-23T15:37:17.541+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T15:37:17.571+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T15:37:07.415167+00:00 [queued]>
[2024-04-23T15:37:17.583+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T15:37:07.415167+00:00 [queued]>
[2024-04-23T15:37:17.584+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-23T15:37:17.601+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): data_quality_check> on 2024-04-23 15:37:07.415167+00:00
[2024-04-23T15:37:17.612+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1823) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-23T15:37:17.615+0000] {standard_task_runner.py:63} INFO - Started process 1832 to run task
[2024-04-23T15:37:17.615+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'data_quality_check', 'manual__2024-04-23T15:37:07.415167+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp4uuz8tdy']
[2024-04-23T15:37:17.616+0000] {standard_task_runner.py:91} INFO - Job 134: Subtask data_quality_check
[2024-04-23T15:37:17.677+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T15:37:07.415167+00:00 [running]> on host ec31c9b90297
[2024-04-23T15:37:17.837+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='data_quality_check' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T15:37:07.415167+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T15:37:07.415167+00:00'
[2024-04-23T15:37:17.840+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T15:37:18.478+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-23T15:37:18.479+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T15:37:18.491+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=model_pipeline, task_id=data_quality_check, execution_date=20240423T153707, start_date=20240423T153717, end_date=20240423T153718
[2024-04-23T15:37:18.555+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-23T15:37:18.592+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-23T15:37:18.595+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
